### ISSUE TITLE
Konfiguracja nginx, tak by wszystkie serwisy - jenkins, gerrit, homepage były na jednym porcie

### ISSUE THREAD

**Issue by Wasiollo** [PIKSilentPenguins/OpenFoosball#5]

**Comment by tranzystorekk** [comment]
Serwisy muszą być koniecznie na jednym porcie?

**Comment by Wasiollo** [comment]
Nie ale ja wciąż nie mogę dobić się do jenkinsa. Przydałaby się jakaś jasna tabela chociażby tu w projekcie co i na jakim porcie stoi

**Comment by Wasiollo** [comment]
Nie stawiamy na jednym porcie - decyzja projektowa.
