### ISSUE TITLE
Spotkanie w Epoint - 26.03.2018

### ISSUE THREAD

**Issue by Wasiollo** [PIKSilentPenguins/OpenFoosball#6]

**Comment by tranzystorekk** [comment]
Wymagania dotyczące projektu:
 * aplikacja wspierająca organizację gry w piłkarzyki
 * rejestrujemy graczy pojedyczno
 * definujemy mecze dwóch prar
 * wpisujemy wyniki meczy (dwumecz, mecz jednorundowy)
 * prowadzimy ranking graczy [ilośc zwycięstw, zwycięstwa - porażki]
 * każdy gracz ma swój profil - fota, ilość wygranych, ilość przegranych
 * turnieje jako opcjonalny feature
 * użytkownicy logują się do systemu (login with facebook, github)

Technologie:
 * technologie wymienione są ok
 * Angular/Bootstrap na froncie
 * GitHub
 * Budowanie mavenem lub gradlem
 * Serwer CI - jenkins
 * Github jako ITS
 * jacoco, ale możę być coś innego
